version: "3.9"
services:
  frontend:
    container_name: frontend
    restart: always
    ports:
      - "3000:3000"
    build:
      context: packages/app
      dockerfile: Dockerfile
    volumes:
      - ./packages/app:/app
      - /packages/app/node_modules
      - /packages/app/.next
    env_file:
      - .env
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
